---
version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
    - "postgres"

  postgres:
    image: postgres
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example_db